### ISSUE TITLE
Is the license "BSD 3" or "Apache 2.0"?

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomo#411]
This is probably not urgent, but something I noticed and figured was worth pointing out.

The license in github shows it being `BSD 3-Clause "New" or "Revised" License`: https://github.com/DiamondLightSource/httomo/blob/main/LICENSE, but there are some python source files which state the license being `Apache License, Version 2.0`: https://github.com/DiamondLightSource/httomo/blob/f7f4d96508b5e757a42f22bc10e93bec319854a9/httomo/methods_database/packages/external/httomolibgpu/supporting_funcs/recon/algorithm.py#L6-L10

The two licenses have different names so I'm guessing that they're different licenses (please correct me if this is wrong, I don't know for sure!).

If these two licenses _are_ different, it probably would make sense to make this consistent across the codebase, whatever license is chosen.

**Comment by dkazanc** [comment]
Looking at the Savu's [license](https://github.com/DiamondLightSource/Savu/?tab=License-1-ov-file#readme)  I can see that because of the dependencies such as ASTRA and PyFAI they had to adopt GPLv3 as a part of Apache License 2.0. We do not use ASTRA directly in HTTomo but we're using `httomolibgpu` which should be GPLv3 coming from ToMoBAR, which in turn depends on ASTRA. So in short, we should have a similar license to Savu. I'll try to sort it out now.
