### ISSUE TITLE
Sweep issue for smaller previews 

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#424]
As we previously discussed, it was sensible to limit the size of the preview to 7 slices so that the users would avoid running `sweep` pipelines for big datasets. 

I've noticed that for small and larger previews, Paganin filter gives different results for the **_same_** set of parameters.  This means that parameters found for smaller previews cannot be translated to full volume datasets. I suspect that the reason for this is the Fourier filtering nature of the filter which might behave adaptively based on the frequencies present in the data. And since the data is significantly cropped, it is not representative of the whole dataset. This is just a hypothesis, but the fact remains that the result is different, see the images bellow:

Preview of 20 slices
![image](https://github.com/user-attachments/assets/d95185ec-9bab-4c66-acc1-09da90b69f6c)

Preview of 200 slices
![image](https://github.com/user-attachments/assets/42589658-ddb9-4fb2-8fdd-d4050516b89e)

So I'm suggesting here to extend the strict 7 slices criteria for `preview` when the `sweep` run is terminated with:
`ValueError: Parameter sweep runs support input data containing <= 7 sinogram slices, input data contains 100 slices`

**Two options:**
1. Catching if the method works with projections and potentially increase the limit to 200-300 slices. May be just specifically for Paganin? But I have a slight concern here about the distortion correction method which might also need a larger preview or even the whole projection.
2. Apply the larger limit globally. This has got the drawback if the method works with sinograms, like CoR, then there is no need for so many slices. 

A question, I believe that `sweep` run currently bypasses memory estimators and blocks?

**Comment by dkazanc** [comment]
@yousefmoazzam 
thinking about it more. May be we should make the auto-preview with a small amount of slices to be more adaptive rather than cropping the detector-Y dimension on every occasion. Basically we need to crop it based on the pattern of the method to which  `sweep` is applied. 
For instance, if it is a Paganin method and it works with projections, then `sweep` should be done in full projections space for selected few slices (e.g. 7). But crucially the projections should be complete, not cropped.
If we're working with the sinograms then we slice in sinogram space and few full sinograms are given. 
By doing that we would avoid the problem above. 

So it seems that we actually should ignore the preview given by a user in the loader. Our decision is based on where the sweep is needed, does it make sense?

**Comment by yousefmoazzam** [comment]
Yeah, the idea of ignoring the preview in the loader for a sweep run and cropping based on which pattern the method doing the sweep on is a reasonable idea, and it was something that I considered at the time. There was one thing I wasn't sure about though.

With the example of paganin being a projection pattern method, this approach would perform the sweep on a small subset of full projections (say, 7 projection). So, the previewing is inferred to be taking only 7 projections from the raw data, in order to sweep on the paganin method.

My thinking was this means that no sinogram methods can then go in the pipeline after the projection methods, because the previewing has gotten rid of most projections. And I also thought that most people would gauge how the paganin method has performed by doing a recon on the filtered projections, which I wasn't sure would be possible with only a small subset of the projections?

So, with this idea of inferring the dimension to select the 3/5/7 slices from, how should it work as far as:
- the sweep is on a projection method (thus selecting only a few projections)
- and sinogram methods are wanted to be in the pipeline after the projection methods (where sinogram methods typically need all projections)

Have I misunderstood how the cropping should be done, or anything else?

**Comment by dkazanc** [comment]
I see your point! It is indeed a bit tricky if we want to do recon after Paganin to assess the quality of filtering in the reconstruction itself. The reconstruction would need all projections being processed/filtered. It it seems that this is what users mostly do unfortunately, they apply Paganin and then reconstruct. 

In that case, we can do a larger preview, but I'm aware that then a) the data might not fit into the memory GPU and CPU b) the preview will still be slightly different compared to the full projection processed. 

We could do some tricks though. For example, we can downsample the data so that it would fit the memory. The downsampling method can be smart about it, downsample to fit the the GPU memory. The second option is to rebin, i.e. reduce the amount of projections, but the recon might have some artifacts because of that. We probably need to experiment with that. 

Any other ideas, on the technical side?

**Comment by dkazanc** [comment]
@yousefmoazzam assuming that the filter kernel size is found, how would you go and provide that information in the `param_sweep_runner`? I think I'm talking about [this](https://github.com/DiamondLightSource/httomo/blob/f6bb8aca8a4fb10cce5dd55c94dff2d0f1d77325/httomo/sweep_runner/param_sweep_runner.py#L26) parameter essentially as it defines how many slices we take in the middle of array? 

I guess from our pipeline we'd need to know if the run [contains](https://github.com/DiamondLightSource/httomo/blob/6fcf035c79836ba09db9b12651e6b0496d21302b/httomo/cli.py#L174) `sweep` and does it contain Paganin filter? So then in the [pipeline](https://github.com/DiamondLightSource/httomo/blob/6fcf035c79836ba09db9b12651e6b0496d21302b/httomo/cli.py#L183) generation we could perform estimation of the kernel size and make that available somehow in the sweep runner? Should this parameter be passed from `cli.py` to `execute_sweep_run(pipeline, global_comm)`? 

On the second thought, this kernel width estimation module, where do you think it should be? May be an overkill in this instance, but should it be similar to how we estimate memory, padding, i.e. in the library file? Therefore every method returns the previewing size and the max over all the values is taken? Most of the methods will be direct modules returning 7 (as now), but Paganin will be returning a calculation of the filter width?  I believe the function can be written on the CPU without the need of calling the functions from httomolibgpu, if this is an issue?

**Comment by dkazanc** [comment]
a possible drawback of the latter approach is that the kernel size will be estimated every time Paganin filter is present in the pipeline, also for non-sweep pipelines. Which makes this calculation sort of redundant. 
However, having played with the code for kernel size estimation, I think it can be useful information to provide to the user that the kernel is too big, e.g., larger than the half size of the image. Even for normal pipelines this info should go into the log as there is probably something wrong with the input parameters of the filter.

**Comment by yousefmoazzam** [comment]
> @yousefmoazzam assuming that the filter kernel size is found, how would you go and provide that information in the `param_sweep_runner`? I think I'm talking about [this](https://github.com/DiamondLightSource/httomo/blob/f6bb8aca8a4fb10cce5dd55c94dff2d0f1d77325/httomo/sweep_runner/param_sweep_runner.py#L26) parameter essentially as it defines how many slices we take in the middle of array?
> 
> I guess from our pipeline we'd need to know if the run [contains](https://github.com/DiamondLightSource/httomo/blob/6fcf035c79836ba09db9b12651e6b0496d21302b/httomo/cli.py#L174) `sweep` and does it contain Paganin filter? So then in the [pipeline](https://github.com/DiamondLightSource/httomo/blob/6fcf035c79836ba09db9b12651e6b0496d21302b/httomo/cli.py#L183) generation we could perform estimation of the kernel size and make that available somehow in the sweep runner? Should this parameter be passed from `cli.py` to `execute_sweep_run(pipeline, global_comm)`?

The `_sino_slices_threshold` attribute was simply hardcoded in the class because I assumed it wouldn't change. Due to that assumption turning out to be incorrect, I think a sensible thing to do would be to make it a parameter to the sweep runner constructor, something like:
```python
class ParamSweepRunner:
    def __init__(
        self,
        pipeline: Pipeline,
        comm: Comm,
        side_output_manager: SideOutputManager = SideOutputManager(),
        sino_slices_threshold: int = 7,
    ) -> None:
        self._sino_slices_threshold = sino_slices_threshold
        self._pipeline = pipeline
        self._side_output_manager = side_output_manager
```

As you noted, the kernel estimation would need to be known prior to the sweep runner object being created. If this is possible, then I'd say go with that approach. If it's not possible, then we need to rethink how the sweep runner is given that info.

> On the second thought, this kernel width estimation module, where do you think it should be? May be an overkill in this instance, but should it be similar to how we estimate memory, padding, i.e. in the library file? Therefore every method returns the previewing size and the max over all the values is taken? Most of the methods will be direct modules returning 7 (as now), but Paganin will be returning a calculation of the filter width? I believe the function can be written on the CPU without the need of calling the functions from httomolibgpu, if this is an issue?

I agree that having this kernel estimation as a "supporting function" for methods. "Sweep max slices" seems a bit too weird to be a property assigned to each method that needs to be in the methods database.

If we're able to determine before the sweep runner is created:
- if paganin is in the pipeline
- if it's a sweep pipeline

and we're able to pass in `sino_slices_threshold` into the sweep runner constructor, why not just do an if/else, like:
```python
if contains_paganin_method and is_sweep_pipeline:
    runner = ParamSweepRunner(sino_slices_threshold=paganin_kernel_size_estimation, ...)
else:
    runner = ParamSweepRunner(sino_slices_threshold=7, ...)
```
