### ISSUE TITLE
Dealing with the GPU memory limitations

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomo#92]
A possible workaround to deal with big arrays and and not enough of GPU memory. Please come with suggestions. 

1. **httomo** should be able to pre-calculate all data I/O dimension shapes (especially with padding enabled) and data types for **all** methods in the pipeline and store them in the dictionary, e.g., `pipeline_datasets_shapes`.

2.  Enable **httomolib** functionality to assess the amount of memory each method needs depending on its parameters, input shape and data type. A bit uncertain how to organise this technically as the class seems to be the logical way forward but we're trying to preserve the current structure? Basically we need a function (e.g. `_calculate_memory(method_name, data_shape, data_type, *args)`) that would take the name of the method, data shape, data type and parameters and return a scalar (bytes?).
We can use the  `pipeline_datasets_shapes` dictionary to feed information about data shapes and types into `_calculate_memory` function of **httomolib**. 

3.  In  **httomo** we get  the memory limit in bytes for each method in the beginning of the run (right after 1 is complete) and form a new dictionary, e.g., `pipeline_datasets_blocks` which we pass to the wrapper to do data streaming. 

4.  In **httomo** wrapper we organise the streaming of data based on the `pipeline_datasets_blocks` provided.

**Comment by team-gpu** [comment]
Just a few thoughts here:

- for each method, there is one of the 3 dimensions that the data can be chunked in, e.g. in projections, the chunks have to be in the first dimension, etc.
- So the question to the methods could also be phrased as: "Given dimensions (`X`, 123, 151), what is the maximum value of `X` that you can handle within the memory bound M?"

Based on that info from each method, **httomo** should be able to determine a maximum block size it can use for each section of the pipeline between loading, reslicings, and saving. That is, from load to first reslice, all methods may work on projections and use the same chunk size to process all inputs. Same then from reslice to next reslice (or end of pipeline). 

Re using classes or sticking to functions - I think if you wanna keep it functional, you could define a decorator and use that. E.g.:

```
@processing_method(memory=_normalize_memory, pattern='projection', ...)
def normalize(data, ...):
   pass
```

And somehow use the decorator to add extra properties or flags to the method that wrapper can use to get the metadata or call the functions for determining memory, etc. ... Those decorators could also be used to populate a global registry with method names and their properties, etc. btw.

**Comment by team-gpu** [comment]
I have picked up the thoughts above and pushed a suggestion regarding the memory calculation and decorators. Please have a look here: https://github.com/team-gpu/httomolib/commit/f91441b673b363bbf165f4b32b63c8ae8b074985 

Key questions for you:

1. This assumes that the memory calculation function parameter `available_memory` has already been adjusted for the fixed-size parameters, such as `darks` and `flats` - it is only computing the maximum number of slices considering the main input/output + internal temporaries that it needs. Does that make sense?

2. The decorator also trades the module name, module location, and patterrn (`sinogram`, `projection`, `all`). That was added because it's so straightforward to do. As it stands, it could completely replace the [database for httomolib](https://github.com/DiamondLightSource/httomo/blob/main/httomo/methods_database/packages/tomopy.yaml). For that, the decorator tracks in the `method_registry` global dict the metadata of all the methods that have been decorated. This can be used in the wrappers in place of the database. Note that this is just a suggestion, and we're aware that for tomopy a manual DB is still required. We don't see a problem with that though - at least the decorator pattern makes sure that the method names etc in `httomolib` are always in sync with the code.

What are your thoughts on all this?
